spring.application.name=appointment-service
server.port=${SERVER_PORT:8085}
server.servlet.context-path=/EverCare

spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
spring.cloud.config.fail-fast=false

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/EverCaredb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.init_sql=SET FOREIGN_KEY_CHECKS=0

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
