server.port=${SERVER_PORT:8092}

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/EverCaredb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.web.resources.static-locations=file:./uploads/,classpath:/static/,file:./uploads/activities/

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8089/EverCare}
user.service.url=${USER_SERVICE_URL:http://localhost:8089/EverCare}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
