spring.application.name=ApiGateway
spring.config.import=optional:configserver:http://config-server:8888

spring.cloud.config.override-none=true
server.port=8089

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=Appointment Service
springdoc.swagger-ui.urls[0].url=/swagger-docs/appointment
springdoc.swagger-ui.urls[1].name=Activities Service
springdoc.swagger-ui.urls[1].url=/swagger-docs/activities
springdoc.swagger-ui.urls[2].name=Blog Service
springdoc.swagger-ui.urls[2].url=/swagger-docs/blog
springdoc.swagger-ui.urls[3].name=DailyMe Service
springdoc.swagger-ui.urls[3].url=/swagger-docs/dailyme
springdoc.swagger-ui.urls[4].name=Medical Record Service
springdoc.swagger-ui.urls[4].url=/swagger-docs/medical-record
springdoc.swagger-ui.urls[5].name=Notification Service
springdoc.swagger-ui.urls[5].url=/swagger-docs/notification
